var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var b=$jscomp.propertyToPolyfillSymbol[c];if(null==b)return a[c];b=a[b];return void 0!==b?b:a[c]};$jscomp.polyfill=function(a,c,b,d){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,b,d):$jscomp.polyfillUnisolated(a,c,b,d))};
$jscomp.polyfillUnisolated=function(a,c,b,d){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in b))return;b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,b,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<e.length-1;g++){var k=e[g];if(!(k in d))return;d=d[k]}e=e[e.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?d[e]:null;c=c(b);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:c}):c!==b&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:c})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},c={};try{return c.__proto__=a,c.a}catch(b){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,c){this.nextAddress=c;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,c){a=$jscomp.makeIterator(a);var b=a.next();$jscomp.generator.ensureIteratorResultIsObject_(b);if(b.done)this.yieldResult=b.value,this.nextAddress=c;else return this.yieldAllIterator_=a,this.yield(b.value,c)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,c){this.catchAddress_=a;void 0!=c&&(this.finallyAddress_=c)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,c){this.nextAddress=a;this.catchAddress_=c||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,c,b){b?this.finallyContexts_[b]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=c||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,c){c=this.finallyContexts_.splice(c||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var c in a)this.properties_.push(c);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var c=this.context_.yieldAllIterator_;if(c)return this.yieldAllStep_("return"in c?c["return"]:function(b){return{value:b,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,c,b){try{var d=a.call(this.context_.yieldAllIterator_,c);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;b.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(c){this.context_.yieldResult=void 0,this.context_.throw_(c)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(c){return a.next_(c)};this.throw=function(c){return a.throw_(c)};this.return=function(c){return a.return_(c)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,c){c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(c));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var c=function(e,g){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})};c.prototype.toString=function(){return this.$jscomp$symbol$id_};var b=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+b++,e)};return d},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var c="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),b=0;b<c.length;b++){var d=$jscomp.global[c[b]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.polyfill("Object.is",function(a){return a?a:function(c,b){return c===b?0!==c||1/c===1/b:c!==c&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(c,b){var d=this;d instanceof String&&(d=String(d));var e=d.length;b=b||0;for(0>b&&(b=Math.max(b+e,0));b<e;b++){var g=d[b];if(g===c||Object.is(g,c))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(c,b){return-1!==$jscomp.checkStringArgs(this,c,"includes").indexOf(c,b||0)}},"es6","es3");
$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var g=a[e];if(c.call(b,g,e,a))return{i:e,v:g}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.findIndex",function(a){return a?a:function(c,b){return $jscomp.findInternal(this,c,b).i}},"es6","es3");$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(c,b){return $jscomp.findInternal(this,c,b).v}},"es6","es3");
$jscomp.polyfill("Math.trunc",function(a){return a?a:function(c){c=Number(c);if(isNaN(c)||Infinity===c||-Infinity===c||0===c)return c;var b=Math.floor(Math.abs(c));return 0>c?-b:b}},"es6","es3");$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},c=Object.create(new $jscomp.global.Proxy(a,{get:function(b,d,e){return b==a&&"q"==d&&e==c}}));return!0===c.q}catch(b){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;
$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.owns=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};
$jscomp.polyfill("WeakMap",function(a){function c(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),m=Object.seal({}),l=new a([[h,2],[m,3]]);if(2!=l.get(h)||3!=l.get(m))return!1;l.delete(h);l.set(m,4);return!l.has(h)&&4==l.get(m)}catch(p){return!1}}function b(){}function d(h){var m=typeof h;return"object"===m&&null!==h||"function"===m}function e(h){if(!$jscomp.owns(h,k)){var m=new b;$jscomp.defineProperty(h,k,{value:m})}}function g(h){if(!$jscomp.ISOLATE_POLYFILLS){var m=Object[h];m&&(Object[h]=
function(l){if(l instanceof b)return l;Object.isExtensible(l)&&e(l);return m(l)})}}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(c())return a;var k="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var n=0,f=function(h){this.id_=(n+=Math.random()+1).toString();if(h){h=$jscomp.makeIterator(h);for(var m;!(m=h.next()).done;)m=m.value,this.set(m[0],m[1])}};f.prototype.set=function(h,m){if(!d(h))throw Error("Invalid WeakMap key");
e(h);if(!$jscomp.owns(h,k))throw Error("WeakMap key fail: "+h);h[k][this.id_]=m;return this};f.prototype.get=function(h){return d(h)&&$jscomp.owns(h,k)?h[k][this.id_]:void 0};f.prototype.has=function(h){return d(h)&&$jscomp.owns(h,k)&&$jscomp.owns(h[k],this.id_)};f.prototype.delete=function(h){return d(h)&&$jscomp.owns(h,k)&&$jscomp.owns(h[k],this.id_)?delete h[k][this.id_]:!1};return f},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function c(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),h=new a($jscomp.makeIterator([[f,"s"]]));if("s"!=h.get(f)||1!=h.size||h.get({x:4})||h.set({x:4},"t")!=h||2!=h.size)return!1;var m=h.entries(),l=m.next();if(l.done||l.value[0]!=f||"s"!=l.value[1])return!1;l=m.next();return l.done||4!=l.value[0].x||"t"!=l.value[1]||!m.next().done?!1:!0}catch(p){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(c())return a;var b=new WeakMap,d=function(f){this.data_={};this.head_=k();this.size=0;if(f){f=$jscomp.makeIterator(f);for(var h;!(h=f.next()).done;)h=h.value,this.set(h[0],h[1])}};d.prototype.set=function(f,h){f=0===f?0:f;var m=e(this,f);m.list||(m.list=this.data_[m.id]=[]);m.entry?m.entry.value=h:(m.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:f,value:h},m.list.push(m.entry),
this.head_.previous.next=m.entry,this.head_.previous=m.entry,this.size++);return this};d.prototype.delete=function(f){f=e(this,f);return f.entry&&f.list?(f.list.splice(f.index,1),f.list.length||delete this.data_[f.id],f.entry.previous.next=f.entry.next,f.entry.next.previous=f.entry.previous,f.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=k();this.size=0};d.prototype.has=function(f){return!!e(this,f).entry};d.prototype.get=function(f){return(f=
e(this,f).entry)&&f.value};d.prototype.entries=function(){return g(this,function(f){return[f.key,f.value]})};d.prototype.keys=function(){return g(this,function(f){return f.key})};d.prototype.values=function(){return g(this,function(f){return f.value})};d.prototype.forEach=function(f,h){for(var m=this.entries(),l;!(l=m.next()).done;)l=l.value,f.call(h,l[1],l[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var e=function(f,h){var m=h&&typeof h;"object"==m||"function"==m?b.has(h)?m=b.get(h):
(m=""+ ++n,b.set(h,m)):m="p_"+h;var l=f.data_[m];if(l&&$jscomp.owns(f.data_,m))for(f=0;f<l.length;f++){var p=l[f];if(h!==h&&p.key!==p.key||h===p.key)return{id:m,list:l,index:f,entry:p}}return{id:m,list:l,index:-1,entry:void 0}},g=function(f,h){var m=f.head_;return $jscomp.iteratorPrototype(function(){if(m){for(;m.head!=f.head_;)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:h(m)};m=null}return{done:!0,value:void 0}})},k=function(){var f={};return f.previous=f.next=f.head=f},n=0;
return d},"es6","es3");
$jscomp.polyfill("Set",function(a){function c(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),e=new a($jscomp.makeIterator([d]));if(!e.has(d)||1!=e.size||e.add(d)!=e||1!=e.size||e.add({x:4})!=e||2!=e.size)return!1;var g=e.entries(),k=g.next();if(k.done||k.value[0]!=d||k.value[1]!=d)return!1;k=g.next();return k.done||k.value[0]==d||4!=k.value[0].x||k.value[1]!=k.value[0]?!1:g.next().done}catch(n){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(c())return a;var b=function(d){this.map_=new Map;if(d){d=$jscomp.makeIterator(d);for(var e;!(e=d.next()).done;)this.add(e.value)}this.size=this.map_.size};b.prototype.add=function(d){d=0===d?0:d;this.map_.set(d,d);this.size=this.map_.size;return this};b.prototype.delete=function(d){d=this.map_.delete(d);this.size=this.map_.size;return d};b.prototype.clear=function(){this.map_.clear();this.size=0};b.prototype.has=
function(d){return this.map_.has(d)};b.prototype.entries=function(){return this.map_.entries()};b.prototype.values=function(){return this.map_.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(d,e){var g=this;this.map_.forEach(function(k){return d.call(e,k,k,g)})};return b},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(c,b,d){var e=this.length||0;0>b&&(b=Math.max(0,e+b));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(b=Number(b||0);b<d;b++)this[b]=c;return this}},"es6","es3");$jscomp.typedArrayFill=function(a){return a?a:Array.prototype.fill};$jscomp.polyfill("Int8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint8Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Uint8ClampedArray.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint16Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Int32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Uint32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");$jscomp.polyfill("Float32Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");
$jscomp.polyfill("Float64Array.prototype.fill",$jscomp.typedArrayFill,"es6","es5");var app_config={test_percent_cap:100,chunk:300,useCredentials:!0,URLprefix:"https://bannerxe.is.colostate.edu/StudentRegistrationSsb/ssb/"},GETPOST;app_config.URLgetTerms=function(a){a.openMethod="GET";a.url=app_config.URLprefix+"classSearch/getTerms?searchTerm=&offset=1&max=100&_=1600878705085"};
app_config.URLgetCourses=function(a,c,b,d){a.openMethod="GET";a.url=app_config.URLprefix+"searchResults/searchResults?mepCode=CSU&txt_term="+c+"&startDatepicker=&endDatepicker=&pageOffset="+b+"&pageMaxSize="+d.toString()+"&sortColumn=subjectDescription&sortDirection=asc"};app_config.URLgetDescription=function(a,c,b){a.openMethod="POST";a.url=app_config.URLprefix+"searchResults/getCourseDescription";a.postData="term="+c+"&courseReferenceNumber="+b};
app_config.URLgetCourseTotalCount=function(a,c){a.openMethod="GET";a.url=app_config.URLprefix+"searchResults/searchResults?mepCode=CSU&txt_term="+c+"&startDatepicker=&endDatepicker=&pageOffset=0&pageMaxSize=10&sortColumn=subjectDescription&sortDirection=asc"};app_config.URLtest=function(a){a.openMethod="GET";a.url=app_config.URLprefix};app_config.URLprime=function(a,c){a.openMethod="POST";a.url=app_config.URLprefix+"term/search?mode=search";a.postData="term="+c+"&studyPath=&studyPathText=&startDatepicker=&endDatepicker="};
var Term;app_config.PROCESSgetTerms=function(a){var c=[];JSON.parse(a).forEach(function(b){c.push({URLcode:b.code,title:b.description})});return c};app_config.PROCESSgetCourseTotalCount=function(a){"false"==JSON.parse(a).success&&console.trace("there's something wrong!");return JSON.parse(a).totalCount};var Meeting,Course;
app_config.PROCESSgetCourses=function(a){var c=[];JSON.parse(a).data.forEach(function(b){var d={};d.courseNumber=b.courseNumber;d.URLcode=b.courseReferenceNumber;d.courseRegistrationCode=b.courseReferenceNumber;d.title=b.courseTitle;d.credits=0;void 0!=b.creditHours?d.credits=b.creditHours:void 0!=b.creditHourLow?d.credits=b.creditHourLow:void 0!=b.creditHourHigh&&(d.credits=b.creditHourHigh);d.faculty=void 0===b.faculty||0==b.faculty.length?"STAFF":b.faculty.map(function(e,g,k){return(1<k.length&&
g==k.length-1?"and ":"")+e.displayName.split(", ").reverse().join(" ")}).join(", ");d.scheduleTypeDescription=b.scheduleTypeDescription;d.subject=b.subject;d.maximumEnrollment=b.maximumEnrollment;d.seatsAvailable=b.seatsAvailable;d.waitAvailable=b.waitAvailable;d.waitCapacity=b.waitCapacity;d.meetings=void 0!==b.meetingsFaculty?b.meetingsFaculty.map(function(e){return{building:e.meetingTime.building,room:e.meetingTime.room,beginTime:e.meetingTime.beginTime,endTime:e.meetingTime.endTime,monday:e.meetingTime.monday,
tuesday:e.meetingTime.tuesday,wednesday:e.meetingTime.wednesday,thursday:e.meetingTime.thursday,friday:e.meetingTime.friday,saturday:e.meetingTime.saturday,sunday:e.meetingTime.sunday}}):[];c.push(d)});return c};app_config.PROCESSgetDescription=function(a){for(a=a.replace(/<br>/g,"\r\n").replace(/<BR>/g,"\r\n").trim();"\r\n"==a.substr(0,2);)a=a.substr(2,a.length);for(;"\r\n"==a.substr(a.length-2,a.length-1);)a=a.substr(0,a.length-2);return a};app_config.collegeName="Colorado State University";
app_config.collegeNameShort="CSU";app_config.siteTitle="CSU Scheduler - Course Scheduler for Colorado State University";app_config.siteTitleShort="CSU Scheduler";app_config.courseRegistrationCodeName="CRN";app_config.getLogoName=function(a){return"CSU-Signature-Stacked-357-617"+(a?"-rev":"")+".svg"};app_config.CORStest=!0;app_config.CORScustom="The developer ran out of hosting credits on a free trial. Sorry but I'm not paying to make this easy for you.";document.title=app_config.siteTitle;
!0===app_config.CORStest?document.getElementById("cors").innerHTML="Hi, and welcome to "+app_config.siteTitleShort+"! This is a tool for creating, editing, testing, and sharing schedules for "+app_config.collegeName+".<br><br>I can see you're locked out of the "+app_config.collegeNameShort+" systems. Unfortunately, there isn't anything the developer can do about this problem. This is because "+app_config.collegeNameShort+" won't recognize this website as friendly.<br><b>In order to use this tool, please download and use a CORS-everywhere extension</b> and refresh. This intercepts data coming from "+app_config.collegeNameShort+
"'s servers and makes your browser think "+app_config.collegeNameShort+' trusts us, so that your browser doesn\'t lock you out. Here are a few I recommend:<br><a href="https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/">Firefox</a><br>For Chrome, it\'s a bit more envolved. See <a href="https://www.codevoila.com/post/75/how-to-disable-same-origin-policy-in-chrome">this</a> for more details.<br>NOTE: it is technically unsafe to browse with CORS-everywhere enabled. Please, disable it when not using this tool.<br><br><b>'+
app_config.CORScustom+"</b>":document.getElementById("cors").innerHTML="Hi, and welcome to "+app_config.siteTitleShort+"! This is a tool for creating, editing, testing, and sharing schedules for "+app_config.collegeName+".<br><br><b>The "+app_config.collegeNameShort+" servers seem to be down right now. Check back later.</b><br><br>If you're a developer, this might be a CORS related issue.";
(function(){for(var a=document.getElementById("schedThead"),c="Monday Tuesday Wednesday Thursday Friday Saturday Sunday".split(" "),b=0;b<c.length;++b){var d=c[b],e=document.createElement("th");e.innerText=d;a.appendChild(e)}})();
(function(){var a=document.getElementById("schedTbody"),c=[8,9,10,11,12,13,14,15,16,17,18,19,20],b="monday tuesday wednesday thursday friday saturday sunday".split(" "),d=document.createElement("tr"),e=document.createElement("td");e.className="time";d.appendChild(e);e=document.createElement("td");e.className="block";var g=document.createElement("div");g.className="wrapper";var k=document.createElement("div");k.className="wrapperInternal";g.appendChild(k);g.appendChild(document.createElement("div"));
g.appendChild(document.createElement("div"));e.appendChild(g);for(g=0;g<c.length;++g){k=c[g];var n=d.cloneNode(!0);n.firstChild.innerText=(k-1)%12+1+":00";for(var f=0;f<b.length;++f){var h=b[f],m=e.cloneNode(!0);m.firstChild.firstChild.setAttribute("data-hour",k);m.firstChild.firstChild.setAttribute("data-day",h);n.appendChild(m)}a.appendChild(n)}})();
(function(){var a=document.getElementById("schedThead").children;a[6].style.display="none";a[7].style.display="none";a=document.getElementById("schedTbody").children;for(var c=0;c<a.length;++c)a[c].children[6].style.display="none",a[c].children[7].style.display="none"})();window.onresize=function(){var a=document.getElementById("weekTableWrapper");document.getElementById("weekTableHead").style.borderRight=(a.offsetWidth-a.clientWidth).toString()+"px solid "+getComputedStyle(document.getElementById("schedThead")).backgroundColor};var postProcessCourses=function(a){return a.filter(function(c){return c.meetings.reduce(function(b,d){return b||"monday tuesday wednesday thursday friday saturday sunday".split(" ").reduce(function(e,g){return e||d[g]},!1)||"ONLINE"==d.building},!1)}).map(function(c){c.scheduleTypeDescription.includes("Honors ")&&(c.scheduleTypeDescription=c.scheduleTypeDescription.split("Honors ")[1]);return c}).reduce(function(c,b){return 0<c.length?(c[c.length-1][0].subject+c[c.length-1][0].courseNumber==b.subject+
b.courseNumber?c[c.length-1].push(b):c.push([b]),c):[[b]]},[]).map(function(c){c[0].home=c[0];c[0].alts=[[c[0]]];for(var b=1;b<c.length;++b){c[b].home=c[0];var d=c[0].alts.findIndex(function(e){return e[0].scheduleTypeDescription==c[b].scheduleTypeDescription});-1<d?c[0].alts[d].push(c[b]):c[0].alts.push([c[b]])}return c}).reduce(function(c,b){return c.concat(b)},[]).map(function(c,b){c.index=b;return c})},Searcher=function(a,c,b,d){this.term=void 0===c?"":c;this.data=[];this.done=!1;this.offset=
void 0===b?"":b;this.size=void 0===d?0:d;this.xhr=null;this.type=a};
Searcher.prototype.start=function(a,c){a=void 0===a?null:a;c=void 0===c?null:c;if(!this.xhr&&!this.done){var b={postData:"0",openMethod:"",url:""};switch(this.type){case "prime":app_config.URLprime(b,this.term);break;case "count":app_config.URLgetCourseTotalCount(b,this.term);break;case "courses":app_config.URLgetCourses(b,this.term,this.offset.toString(),this.size);break;case "terms":app_config.URLgetTerms(b);break;case "desc":app_config.URLgetDescription(b,this.term,this.offset.toString());break;
case "test":app_config.URLtest(b);break;default:console.error("Invalid type in Searcher")}if(""==b.url){if("prime"==this.type||"count"==this.type){this.xhr=null;this.done=!0;a(!1);return}console.error("url not set for request of type "+this.type+". There's an erorr in config.js")}""==b.openMethod&&console.error("openMethod not set for request of type "+this.type+". There's an erorr in config.js");"POST"==b.openMethod&&"0"==b.postData&&console.error("postData is missing for POST request of type "+
this.type+". There's an erorr in config.js");this.xhr=new XMLHttpRequest;this.xhr.onreadystatechange=function(d){return function(){4==this.readyState&&(this.done=!0,d.xhr=null);"test"==d.type&&4===this.readyState&&0===this.status?(!0===app_config.CORStest?console.error("CORS DENIED - please enable a CORS-everywhere extension or ask "+app_config.collegeNameShort+" to let us in"):console.error("Can't communicate with "+app_config.collegeName+" servers. They're probable down right now - check back later."),
a&&a(!1)):"test"==d.type&&4===this.readyState?a&&a(!0):"test"!=d.type&&(4===this.readyState&&200===this.status?(a&&a(this.responseText),d.done=!0,d.xhr=null):200!=this.status&&4==this.readyState&&(c?c(this.status,this.responseText):console.error("Unhandled erorr on HTTP request: ",this.status.toString())))}}(this);this.xhr.open(b.openMethod,b.url);this.xhr.withCredentials=app_config.useCredentials;"POST"==b.openMethod&&this.xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
this.xhr.send(b.postData)}};Searcher.prototype.stop=function(){this.xhr&&!this.done&&(this.xhr.abort(),this.xhr=null)};var TermManager=function(a){this.term=a;this.data=[];this.done=!1;this.requests=[];this.headRequest=null;this.main_callback_wrapper={callback:null};this.totalCount=0};
TermManager.prototype.start=function(a,c){c=void 0===c?!1:c;this.main_callback_wrapper.callback=a;this.done?a&&a(this.data):this.headRequest||(a=function(b){return function(d){b.requests.length?(d=b.data.reduce(function(e,g){return e+g.courses.length},0),0!==b.totalCount&&(app.percent=d.toString()+"/"+b.totalCount.toString(),app.updatePercent()),b.headRequest=null,b.requests.forEach(function(e){e.start(function(g){g=app_config.PROCESSgetCourses(g);b.data.push({courses:g,offset:e.offset});g=b.data.reduce(function(f,
h){return f+h.courses.length},0);0!==b.totalCount&&(app.percent=g.toString()+"/"+b.totalCount.toString(),app.updatePercent());if(0===b.totalCount||g>=app_config.test_percent_cap*b.totalCount/100){app.percent+="\nProcessng courses...";app.updatePercent();b.data=postProcessCourses(b.data.sort(function(f,h){return f.offset-h.offset}).reduce(function(f,h){return f.concat(h.courses)},[]));b.done=!0;b.requests=[];b.main_callback_wrapper.callback&&b.main_callback_wrapper.callback(b.data);g=document.getElementById("saves").children;
for(var k=[],n=0;n<g.length;++n)k.push(JSON.parse(window.localStorage.schedules)[g[n].innerText].split("=")[0]);g=app.termCacher.termManagers.filter(function(f){return f.done}).map(function(f){return f.term});for(n=0;n<k.length;++n)if(!g.find(function(f){return f==k[n]})){app.termCacher.push(k[n],null);break}}},function(g,k){404==g&&("Cache not warm"==k&&app.term==b.term?alert("It looks like the server just started recently and has not downloaded data for this term yet. Please try again in a few minutes."):
""!==k&&console.error("Unhandled error "+g+":"+k))})})):(app.percent="0/?",app.updatePercent(),b.headRequest=new Searcher("count",b.term),b.headRequest.start(function(e){b.headRequest=null;if(!1===e)app.percent="",app.updatePercent(),e=new Searcher("courses",b.term,"0",0),e.offset=0,b.requests.push(e);else{b.totalCount=app_config.PROCESSgetCourseTotalCount(e);app.percent="0/"+b.totalCount.toString();app.updatePercent();e=[];for(var g=0;g<app_config.test_percent_cap*b.totalCount/100;g+=app_config.chunk)e.push(g);
e.forEach(function(k){var n=new Searcher("courses",b.term,k,app_config.chunk);n.offset=k;b.requests.push(n)})}b.start(b.main_callback_wrapper.callback,!0)}))}}(this),c?a(null):(this.headRequest=new Searcher("prime",this.term),this.headRequest.start(a)))};TermManager.prototype.stop=function(){this.done||(this.main_callback_wrapper.callback=null,this.headRequest&&(this.headRequest.stop(),this.headRequest=null),this.requests.forEach(function(a){a.stop()}))};
var TermCacher=function(){this.termManagers=[]};
TermCacher.prototype.push=function(a,c){c=void 0===c?null:c;var b=this.termManagers.findIndex(function(e){return e.term==a});if(-1<b&&this.termManagers[b].done)this.termManagers.forEach(function(e){e.main_callback_wrapper.callback=null}),this.termManagers[b].start(c);else{var d=null;-1<b&&(d=this.termManagers.splice(b,1)[0]);this.termManagers.forEach(function(e){e.stop()});this.termManagers.push(-1<b?d:new TermManager(a));this.termManagers[this.termManagers.length-1].start(c)}};var app={course:null,courses:[],selected:[],mode:"Manual",courses_generator:null,savedCourseGenerator:"0",course_list_selection:0,hovering:[],currentstorage:null,terms:[],term:"",courses_auto:"",courses_manual:"",closed:!1,percent:""};app.termCacher=new TermCacher;app.generateHash=function(a){var c=app.term+"=",b=app.selected;"Automatic"===app.mode&&app.courses_generator&&app.courses_generator.data&&app.courses_generator.data[app.course_list_selection]&&(b=app.courses_generator.data[app.course_list_selection].selected);c+=b.sort(function(d,e){return d.URLcode-e.URLcode}).map(function(d){return d.URLcode+(d.locked?"!":"")}).join();app.closed&&(c+="&C");!0===a&&(c+="+"+document.getElementById("notes").value);return c};app.getHash=function(){return decodeURIComponent(location.hash)};
app.changed=function(){if(0==app.selected.length)return!1;for(var a=document.getElementById("saves").children,c=!0,b=-1,d=0;d<a.length;++d)a[d].classList.contains("selected")&&(b=d);if(-1<b)c=JSON.parse(window.localStorage.schedules)[a[b].innerText]!=app.generateHash(!0);else for(d=0;d<a.length;++d)a[d].classList.contains("preselect")&&(c=JSON.parse(window.localStorage.schedules)[a[d].innerText]!=app.generateHash(!0));return c};
app.autoInAlts=function(a,c){return null==a||null==c?!1:"Manual"==app.mode?a==c:a.home==c.home};var gtag;window.addEventListener("keydown",function(a){"Escape"==a.key&&(document.getElementById("selectBox").value="",app.course=null,app.savedCourseGenerator="",app.courses_generator=null,app.fillSchedule())});
var change_style=function(a){for(var c=!1,b=0;b<document.styleSheets.length;++b)null==document.styleSheets[b].href?c=!0:document.styleSheets[b].href.includes("style_dark.min.css")&&(document.styleSheets[b].disabled=!a.checked);c?(window.localStorage.darkMode=!0,document.styleSheets[0].disabled=!0,document.getElementById("logo").src=app_config.getLogoName(!0),a.style.display="none"):(document.getElementById("logo").src=app_config.getLogoName(a.checked),window.localStorage.darkMode=a.checked.toString())};
app.autoAndLabs=function(a){return null==a?[]:"Manual"==app.mode?[a]:app.courses_generator?app.courses_generator.get(app.course_list_selection).filter(function(c){return c&&c.home==a.home}):[]};
app.fillSchedule=function(a){if(a=void 0===a?null:a)app.course_list_selection=a.value;app.course=""!=document.getElementById("selectBox").value?parseInt(document.getElementById("selectBox").value,10):null;var c=document.getElementsByClassName("wrapperInternal"),b=app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null),!0).get("Manual"==app.mode?0:app.course_list_selection);a=[];for(var d=0;d<c.length;++d){for(var e=c[d],g=e.getAttribute("data-day"),k=e.getAttribute("data-hour");e.firstChild;)e.removeChild(e.firstChild);
for(var n=0;n<b.length;++n){var f=b[n],h=app.courseHere(g,k,f);if(f&&h){var m=document.createElement("div");if("Automatic"==app.mode||!app.autoInAlts(f,null!==app.course?app.courses[app.course]:null)){var l=document.createElement("div");l.className="autoLock";l.innerText=f.locked?"\ud83d\udd12":"\ud83d\udd13 ";l.onclick=function(q,u){return function(r){app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null)).get(app.course_list_selection,!0);q.locked=!q.locked;app.savedCourseGenerator=
"";app.fillSchedule();null===app.course||app.autoInAlts(app.courses[app.course],q)||(location.hash=app.generateHash(!1))}}(f,l);l.style.top=100*h.top+"%";m.appendChild(l)}l=document.createElement("div");l.className="item";var p=f.subject+" "+f.courseNumber+"\n"+f.title.replace(/&ndash;/g,"\u2013")+"\n"+(f.faculty.trim().length?f.faculty+"\n":"")+(h.loc.length?h.loc+"\n":"")+f.credits+" credit"+(1!=f.credits?"s":"")+"\n";void 0!==f.seatsAvailable&&void 0!==f.maximumEnrollment&&(p+=Math.max(0,f.seatsAvailable)+
"/"+f.maximumEnrollment+" seats open\n");void 0!==f.waitAvailable&&void 0!==f.waitAvailable&&(p+=f.waitAvailable+"/"+f.waitCapacity+" waitlist open\n");p+=app_config.courseRegistrationCodeName+": "+f.courseRegistrationCode+"\n";l.innerText=p;p=document.createElement("a");p.className="link";p.onclick=function(q){return function(){app.fetchDescription(q)}}(f);p.innerText="Description";l.appendChild(p);l.setAttribute("data-index",f.index);l.setAttribute("data-length",h.length);l.setAttribute("data-top",
h.top);app.autoInAlts(f,null!==app.course?app.courses[app.course]:null)||l.classList.add("selected");l.style.top=100*l.getAttribute("data-top")+"%";l.style.height=app.hovering.includes(f)?"auto":100*l.getAttribute("data-length")+"%";l.style.minHeight=app.hovering.includes(f)?100*l.getAttribute("data-length")+"%":"auto";!app.closed&&"Manual"==app.mode&&!f.locked&&0>=f.seatsAvailable&&(f=document.createElement("div"),f.className="closedAlign",h=document.createElement("div"),h.className="closedMsg",
h.innerText="CLOSED",f.appendChild(h),l.insertBefore(f,l.childNodes[0]));m.appendChild(l);e.appendChild(m);a.push(l)}}}n=document.getElementById("webWrapper");for(c=document.getElementById("web");c.firstChild;)c.removeChild(c.firstChild);b=Array.isArray(b)?app.webclasses(b):[];n.style.display=b.length?"":"none";for(n=0;n<b.length;++n)if(f=b[n])m=document.createElement("div"),"Automatic"!=app.mode&&app.autoInAlts(f,null!==app.course?app.courses[app.course]:null)||(l=document.createElement("div"),l.className=
"autoLock",l.innerText=f.locked?"\ud83d\udd12":"\ud83d\udd13 ",l.onclick=function(q){return function(u){app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null)).get(app.course_list_selection,!0);q.locked=!q.locked;app.savedCourseGenerator="";app.fillSchedule();null===app.course||app.autoInAlts(app.courses[app.course],q)||(location.hash=app.generateHash(!1))}}(f),m.appendChild(l)),l=document.createElement("div"),l.className="item",p=f.subject+" "+f.courseNumber+"\n"+f.title.replace(/&ndash;/g,
"\u2013")+"\n"+(f.faculty.trim().length?f.faculty+"\n":"")+f.credits+" credit"+(1!=f.credits?"s":"")+"\n",void 0!==f.seatsAvailable&&void 0!==f.maximumEnrollment&&(p+=Math.max(0,f.seatsAvailable)+"/"+f.maximumEnrollment+" seats open\n"),void 0!==f.waitAvailable&&void 0!==f.waitAvailable&&(p+=f.waitAvailable+"/"+f.waitCapacity+" waitlist open\n"),p+=app_config.courseRegistrationCodeName+": "+f.courseRegistrationCode+"\n",l.innerText=p,p=document.createElement("a"),p.className="link",p.onclick=function(q){return function(){app.fetchDescription(q)}}(f),
p.innerText="Description",l.appendChild(p),l.setAttribute("data-index",f.index),app.autoInAlts(f,null!==app.course?app.courses[app.course]:null)||l.classList.add("selected"),m.appendChild(l),!app.closed&&"Manual"==app.mode&&!f.locked&&0>=f.seatsAvailable&&(d=document.createElement("div"),d.className="closedAlign",e=document.createElement("div"),e.className="closedMsg",e.innerText="CLOSED",d.appendChild(e),l.insertBefore(d,l.childNodes[0])),c.appendChild(m),a.push(l);var w=function(q){return function(){for(var u=
0;u<q.length;++u){var r=q[u],t=app.courses[r.getAttribute("data-index")];app.autoInAlts(t,null!==app.course?app.courses[app.course]:null)?r.classList.remove("selected"):r.classList.add("selected");var v=r.parentElement.getElementsByClassName("autoLock");null!==t&&app.hovering.includes(t)?(v.length&&v[0].classList.add("hovering"),r.classList.add("hovering")):(v.length&&v[0].classList.remove("hovering"),r.classList.remove("hovering"));r.getAttribute("data-top")&&(r.style.top=100*r.getAttribute("data-top")+
"%",r.style.height=null!==t&&app.hovering.includes(t)?"auto":100*r.getAttribute("data-length")+"%",r.style.minHeight=null!==t&&app.hovering.includes(t)?100*r.getAttribute("data-length")+"%":"auto")}}}(a);w();for(n=0;n<a.length;++n)a[n].ondblclick=function(q){return function(){app.click(q);app.course=null;document.getElementById("selectBox").value=""}}(app.courses[a[n].getAttribute("data-index")]),a[n].parentElement.onmouseover=function(q){return function(){app.hovering=app.autoAndLabs(q);w()}}(app.courses[a[n].getAttribute("data-index")]),
a[n].parentElement.onmouseout=function(){return function(){app.hovering=[];w()}}();app.dayUpdate();app.autoBar();app.saveMarker();app.updateCredits();document.getElementById("escTip").style.display=null!=app.course?"":"none";window.localStorage.setItem("lastViewed",app.generateHash(!1));0<app.selected.length&&gtag("event","Schedules Tested")};app.disableOnHashChange=!1;
window.onhashchange=function(){app.disableOnHashChange||app.generateHash(!1)==app.getHash().substr(1)||(app.getHash().substr(1).split("=")[0].length?(app.changedTerm("first",{value:app.terms[app.terms.map(function(a){return a.URLcode}).indexOf(app.getHash().split("=")[0].substr(1))].URLcode}),app.updateTerms()):app.clear());app.disableOnHashChange=!1};
app.courseHere=function(a,c,b){if(!b)return null;var d=parseInt(c,10),e=null;b.meetings.forEach(function(g){if("WS"!=g.building&&g.beginTime&&g[a]){var k=app.convertTime(g.beginTime),n=app.convertTime(g.endTime);Math.trunc(k)==d-8&&(e={top:k-Math.trunc(k),length:n-k,loc:g.building&&g.building.trim().length&&g.room&&g.room.trim().length?g.building+" "+g.room:""})}});return e};app.convertTime=function(a){var c=a.substr(-2);return parseFloat(a.substr(0,a.length-c.length))+parseFloat(c)/60-8};
app.webclasses=function(a){return a?a.filter(function(c){return c&&c.meetings.map(function(b){return"ONLINE"==b.building}).reduce(function(b,d){return b||d},!1)}):[]};
app.fetchDescription=function(a){document.getElementById("description-fetch").style.display="";document.getElementById("description-show").style.display="none";document.getElementById("description").style.display="";document.getElementById("description-strong").innerText=a.subject+" "+a.courseNumber+":";var c=function(b){var d=document.getElementById("description-show");d.innerText=b;d.style.display="";document.getElementById("description-fetch").style.display="none"};a.description?c(a.description):
(new Searcher("desc",app.term.toString(),a.URLcode.toString())).start(function(b){b=app_config.PROCESSgetDescription(b);c(b);a.description=b})};
app.dayUpdate=function(){if("Automatic"==app.mode)0==app.selected.length||app.courses_generator&&app.courses_generator.data&&app.courses_generator.data[app.course_list_selection]?document.getElementById("noSchedWrapper").style.display="none":document.getElementById("noSchedWrapper").style.display="";else if(document.getElementById("noSchedWrapper").style.display="none","none"==document.getElementById("schedTbody").children[0].children[1].style.display)for(var a=1;5>=a;++a)for(var c=document.getElementById("schedTbody").children,
b=0;b<c.length;++b)c[b].children[a].style.display="";if(0<(null===app.course?app.selected:app.selected.concat(app.courses[app.course])).filter(function(d){return 0<d.meetings.filter(function(e){return e.saturday||e.sunday}).length}).length)for(document.getElementById("schedThead").children[6].style.display="",c=document.getElementById("schedTbody").children,a=0;a<c.length;++a)c[a].children[6].style.display="";else for(document.getElementById("schedThead").children[6].style.display="none",c=document.getElementById("schedTbody").children,
a=0;a<c.length;++a)c[a].children[6].style.display="none";if(0<(null===app.course?app.selected:app.selected.concat(app.courses[app.course])).filter(function(d){return 0<d.meetings.filter(function(e){return e.sunday}).length}).length)for(document.getElementById("schedThead").children[7].style.display="",c=document.getElementById("schedTbody").children,a=0;a<c.length;++a)c[a].children[7].style.display="";else for(document.getElementById("schedThead").children[7].style.display="none",c=document.getElementById("schedTbody").children,
a=0;a<c.length;++a)c[a].children[7].style.display="none"};
app.loadHash=function(a){a=void 0===a?!1:a;if(app.getHash().split("=")[0].length){var c=app.getHash().split("=")[1].split("&")[0].split(",");app.selected=app.courses.filter(function(e){var g=c.map(function(k){return k.replace("!","")}).indexOf(e.URLcode.toString());-1<g&&(e.locked="!"==c[g][c[g].length-1]);return-1<g});document.getElementById("closedCheck").checked=!!app.getHash().split("&")[1];app.closed=!!app.getHash().split("&")[1];if(a){a=[];for(var b=0,d=document.getElementById("saves").children;b<
d.length;++b)JSON.parse(window.localStorage.schedules)[d[b].innerText].split("+")[0]==app.getHash().split("#")[1]&&a.push(d[b]);b=a.filter(function(e){return JSON.parse(window.localStorage.schedules)[e.innerText].split("+")[0]+"?"+e.innerText==window.localStorage.lastSaved});a.length?((b.length?b[0]:a[0]).classList.add("selected"),app.currentstorage=(b.length?b[0]:a[0]).innerText,document.getElementById("notes").value=JSON.parse(window.localStorage.schedules)[app.currentstorage].split("+")[1]):0<
app.getHash().split("&")[0].split("=")[1].length&&app.generateHash(!1)!=window.localStorage.lastViewed&&gtag("event","Schedules Shared")}}else app.clear()};
app.click=function(a){if(null!==a){if(app.autoInAlts(null!==app.course?app.courses[app.course]:null,a))if(document.getElementById("selectBox").value="","Manual"==app.mode)app.course=null,app.selected.push(a);else{var c=app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null)).get(app.course_list_selection).filter(function(d){return app.autoInAlts(null!==app.course?app.courses[app.course]:null,d)});app.course=null;c.forEach(function(d){return app.selected.push(d)});app.savedCourseGenerator=
"A";app.autoConstruct(app.selected).get(app.course_list_selection,!0)}else{if("Manual"==app.mode)a.locked=!1,app.selected.splice(app.selected.indexOf(a),1);else{c=app.selected.filter(function(d){return a.home==d.home});for(var b=0;b<c.length;++b)c[b].locked=!1;app.selected=app.selected.filter(function(d){return a.home!=d.home})}app.hovering=[]}location.hash=app.generateHash(!1);app.course_list_selection=0;c=document.getElementById("Range");c.max=0;c.value=0;app.hideSearch();app.fillSchedule()}};app.totalCredits=function(){return app.selected.reduce(function(a,c){return a+c.credits},0)};app.updateCredits=function(){document.getElementById("credits").innerText=app.totalCredits()};
app.autoBar=function(){var a=document.getElementById("autoBar");a.style.display="Automatic"==app.mode&&(0<app.selected.length||null!==app.course)&&app.autoConstruct(app.selected.concat(null!==app.course?app.courses[app.course]:null)).get(1,!1)?"block":"none";document.getElementById("nextButton").innerText="Next";"none"==a.style.display?(document.getElementById("selectBox").size=25,document.getElementById("Automatic").style.marginBottom="10px"):(document.getElementById("selectBox").size=24,document.getElementById("Automatic").style.marginBottom=
"0px")};
app.genNext=function(a){if(a){app.courses_generator&&app.courses_generator.get(app.courses_generator.data?app.courses_generator.data.length:0)?app.course_list_selection=(app.courses_generator.data?app.courses_generator.data.length:0)-1:(app.course_list_selection++,app.course_list_selection%=app.courses_generator?app.courses_generator.data.length:0);app.fillSchedule();var c=document.getElementById("Range");c.max=app.courses_generator?app.courses_generator.data.length-1:0;c.value=app.course_list_selection;a.innerText=
app.courses_generator&&app.courses_generator.done?"Loop":"Next"}};
app.changedTerm=function(a,c){a=void 0===a?!1:a;c=void 0===c?null:c;a||null===c||!app.changed()||window.confirm("Are you sure you want to discard your changes?")?1==a||app.clear(!a&&null!==c&&app.changed(),"first"==a)?(c&&(c.firstChild&&""==c.firstChild.value&&c.removeChild(c.firstChild),app.term=c.value),app.term&&(app.course=null,document.getElementById("selectBox").value="",document.getElementById("searchBox").value="",app.selected=[],app.course_list_selection=0,c=document.getElementById("Range"),
c.max=0,c.value=0,app.courses_generator=null,app.savedCourseGenerator="","first"!=a&&app.fillSchedule(),app.percent="",document.getElementById("coursesBox").style.display="none",document.getElementById("loadingCourses").style.display="",app.termCacher.push(app.term,function(b){return function(d){app.courses=d;app.genDivs();app.fillSchedule();app.fillSearch();app.loadHash("first"==b);d=document.getElementById("notes");null!==d&&app.updateNotes(d)}}(a)))):document.getElementById("termSelect").value=
app.term:document.getElementById("termSelect").value=app.term};
app.genDivs=function(a){app.courses_manual="";for(a=0;a<app.courses.length;a++)app.courses_manual+='<option value="'+app.courses[a].index+'">'+app.courses[a].subject+" "+app.courses[a].courseNumber+(app.courses[a].sessionMod?app.courses[a].sessionMod:"")+": "+app.courses[a].title+"</option>";app.courses_auto="";for(a=0;a<app.courses.length;++a)if(0==a||app.courses[a].subject+app.courses[a].courseNumber!=app.courses[a-1].subject+app.courses[a-1].courseNumber)app.courses_auto+='<option value="'+app.courses[a].index+
'">'+app.courses[a].subject+" "+app.courses[a].courseNumber+": "+app.courses[a].title+"</option>";document.getElementById("coursesBox").style.display="";document.getElementById("loadingCourses").style.display="none"};app.updateTerms=function(){for(var a=document.getElementById("termSelect");a.lastChild;)a.removeChild(a.lastChild);for(var c=0;c<app.terms.length;c++){var b=app.terms[c],d=document.createElement("option");d.value=b.URLcode;d.innerText=b.title;a.appendChild(d)}a.value=app.term};
app.updatePercent=function(){document.getElementById("loadingCourses").innerText="Loading Courses... "+app.percent};app.updateNotes=function(a){a&&a.style.height!=a.scrollHeight+25+"px"&&(a.style.height="25px",a.style.height=a.scrollHeight+25+"px",app.saveMarker())};app.fillSearch=function(a){a=void 0===a?null:a;var c=document.getElementById("selectBox"),b=c.value;c.innerHTML=app.autoFilter(a);c.value=b;app.hideSearch()};
app.autoFilter=function(a){app.mode=a?a.value:app.mode;return"Manual"==app.mode?app.courses_manual:app.courses_auto};app.hideSearch=function(a){if(a=void 0===a?null:a)app.closed=a.checked,location.hash=app.generateHash(!1);a=document.getElementById("selectBox").children;for(var c=document.getElementById("searchBox").value.toLowerCase(),b=1;b<a.length;++b)a[b].style.display=app.filterSearch(app.courses[a[b].value],c)?"":"none"};
app.filterSearch=function(a,c){return null===a||-1!==app.selected.indexOf(a)||!app.closed&&("Manual"==app.mode?0>=a.seatsAvailable:a.home.alts.map(function(b){return b.map(function(d){return 0>=d.seatsAvailable}).reduce(function(d,e){return d&&e},!0)}).reduce(function(b,d){return b||d},!1))||c&&!(-1<(a.subject+" "+a.courseNumber).toLowerCase().indexOf(c)||-1<a.title.toLowerCase().indexOf(c)||a.URLcode.toString()==c)||"Automatic"==app.mode&&a.home.alts.reduce(function(b,d){return b.concat(d)},[]).some(function(b){return app.selected.includes(b)})?
!1:!0};var animator={element:void 0,down:function(a){return function(c){window.addEventListener("selectstart",animator.disableSelect);animator.element=a;animator.element.style.position="relative";animator.startX=c.clientX;animator.startY=c.clientY;animator.startCenterX=animator.element.offsetLeft+animator.element.offsetWidth/2;animator.startCenterY=animator.element.offsetTop+animator.element.offsetHeight/2}},move:function(a){if(void 0!==animator.element){animator.element.style.top=(a.clientY-animator.startY).toString()+
"px";animator.element.style.left=(a.clientX-animator.startX).toString()+"px";var c=animator.element.offsetLeft+animator.element.offsetWidth/2;animator.element.nextSibling&&c>animator.element.nextSibling.offsetLeft+animator.element.nextSibling.offsetWidth/2&&(animator.element.parentNode.insertBefore(animator.element.nextSibling,animator.element),animator.startX+=c-animator.startCenterX,animator.startCenterX=c,animator.element.style.left=(a.clientX-animator.startX).toString()+"px");animator.element.previousSibling&&
c<animator.element.previousSibling.offsetLeft+animator.element.previousSibling.offsetWidth/2&&(animator.element.parentNode.insertBefore(animator.element,animator.element.previousSibling),animator.startX+=c-animator.startCenterX,animator.startCenterX=c,animator.element.style.left=(a.clientX-animator.startX).toString()+"px")}},up:function(a){if(void 0!==animator.element){window.removeEventListener("selectstart",animator.disableSelect);animator.element.style.top="auto";animator.element.style.left="auto";
animator.element.style.position="static";if(5<Math.abs(a.clientX-animator.startX)||5<Math.abs(a.clientY-animator.startY)){var c=document.getElementById("saves").children,b=[];for(a=0;a<c.length;++a)b.push([c[a].innerText,JSON.parse(window.localStorage.schedules)[c[a].innerText]]);c={};for(a=0;a<b.length;++a)c[b[a][0]]=b[a][1];window.localStorage.schedules=JSON.stringify(c)}else{b=animator.element.parentElement;for(a=0;a<b.children.length;++a)b.children[a].classList.remove("preselect");animator.element.classList.add("preselect");
c=app.load(animator.element.innerText);for(a=0;a<b.children.length;++a)b.children[a].classList.remove("preselect");if(c){for(a=0;a<b.children.length;++a)b.children[a].classList.remove("selected");animator.element.classList.add("selected");app.saveMarker()}}animator.element=void 0}},disableSelect:function(a){a.preventDefault()}};window.onmouseup=animator.up;window.onmousemove=animator.move;
app.saveMarker=function(){document.getElementById("marker-save").style.display=app.changed()&&app.selected.length?"":"none";document.getElementById("marker-discard").style.display=app.changed()&&app.currentstorage&&app.selected.length?"":"none";document.getElementById("marker-saveAsNew").style.display=app.currentstorage?"":"none";document.getElementById("marker-delete").style.display=app.currentstorage?"":"none";document.getElementById("marker-export").style.display=app.selected.length?"":"none";
document.getElementById("marker-new").style.display=app.currentstorage||app.selected.length?"":"none"};
app.updateSaved=function(){var a=Object.keys(JSON.parse(window.localStorage.schedules));if(a.length){for(var c=document.getElementById("saves"),b=0;b<c.children.length;++b){var d=c.children[b],e=a.findIndex(function(g){return g==d.innerText});-1==e?(c.removeChild(d),--b):a.splice(e,1)}for(b=0;b<a.length;++b)e=document.createElement("div"),e.className="option draggable",e.innerText=a[b],c.appendChild(e);a=c.children;for(b=0;b<a.length;++b)a[b].onmousedown=animator.down(a[b]);for(b=0;b<a.length;++b)c=
a[b],app.currentstorage==c.innerText?c.classList.add("selected"):c.classList.remove("selected");app.saveMarker()}};
app.save=function(){if(!app.currentstorage){var a=window.prompt("Please enter a name for the schedule");if(!a)return;app.currentstorage=a}window.localStorage.schedules||window.localStorage.setItem("schedules","{}");a=JSON.parse(window.localStorage.schedules);void 0==a[app.currentstorage]&&gtag("event","Schedules Created");a[app.currentstorage]=app.generateHash(!0);window.localStorage.setItem("schedules",JSON.stringify(a));window.localStorage.setItem("lastSaved",app.generateHash(!1)+"?"+app.currentstorage);
app.selected=[];app.course_list_selection=0;a=document.getElementById("Range");a.max=0;a.value=0;app.courses_generator=null;app.savedCourseGenerator="";app.loadHash();app.autoBar();app.updateSaved();gtag("event","Schedules Saved")};
app.load=function(a){if(null===a||app.changed()&&!window.confirm("Are you sure you want to discard your changes?"))return!1;app.currentstorage=a;document.getElementById("notes").value=JSON.parse(window.localStorage.schedules)[a].split("+")[1];app.disableOnHashChange=!0;location.hash=JSON.parse(window.localStorage.schedules)[a].split("+")[0];a=app.getHash().split("=")[0].substr(1);a=app.terms.map(function(c){return c.URLcode}).indexOf(a);-1<a&&(app.term!=app.terms[a].URLcode?app.term=app.terms[a].URLcode:
(app.course=null,document.getElementById("selectBox").value=""),app.updateTerms(),app.changedTerm(!0));app.updateNotes(document.getElementById("notes"));app.fillSchedule();window.localStorage.setItem("lastSaved",app.generateHash(!1)+"?"+app.currentstorage);return!0};app.discard=function(){var a=app.currentstorage;app.currentstorage=null;app.changed()&&!app.load(a)?app.currentstorage=a:window.localStorage.setItem("lastSaved","{}")};app.saveNew=function(){app.currentstorage=null;app.save()};
app.deleteSchedule=function(){if(window.confirm("Are you sure you want to delete the schedule "+app.currentstorage+"?")){var a=JSON.parse(window.localStorage.schedules);delete a[app.currentstorage];window.localStorage.setItem("schedules",JSON.stringify(a));app.clear(!0);app.updateSaved();app.fillSchedule();window.localStorage.setItem("lastSaved","{}")}};
app.clear=function(a,c){c=void 0===c?!1:c;if((void 0===a||!a)&&app.changed()&&!window.confirm("Are you sure you want to discard your changes?"))return location.hash=app.generateHash(!1),!1;document.getElementById("selectBox").value="";app.course_list_selection=0;a=document.getElementById("Range");a.max=0;a.value=0;app.courses_generator=null;app.savedCourseGenerator="";c||(location.hash="");document.getElementById("notes").value="";app.course=null;app.selected=[];app.currentstorage=null;app.updateSaved();
app.fillSchedule();app.hideSearch();window.localStorage.setItem("lastSaved","{}");return!0};app.showExport=function(){document.getElementById("export").style.display="";document.getElementById("export-link").value=location.href;document.getElementById("export-text").value=app.selected.map(function(a){return a.courseRegistrationCode+": "+a.subject+" "+a.courseNumber}).join("\n")};var Lazy=function(a){this.core=a;this.data=[];this.filters=[];this.done=!1};
Lazy.prototype.get=function(a,c){c=void 0===c?!1:c;if(Array.isArray(this.core))return this.core;for(;!this.done&&this.data.length<=a;){var b=this.core.next();if(b.done){this.done=!0;break}this.filters.reduce(function(d,e){return d&&e(b.value)},!0)&&this.data.push({value:b.value,selected:b.value.filter(function(d){return!d.home.alts.reduce(function(e,g){return e.concat(g)},[]).includes(null!==app.course?app.courses[app.course]:null)})})}a=this.data[a];if(!a)return!1;c&&(app.selected=a.selected);location.hash=
app.generateHash(!1);return a.value};Lazy.prototype.filter=function(a){this.filters.push(a);return this};
app.autoConstruct=function(a,c){c=void 0===c?!1:c;if(void 0===a[0]||null===a[0])return new Lazy([]);void 0!==a.slice(-1)[0]&&null!==a.slice(-1)[0]||a.pop();if("Manual"==app.mode){a=app.closed||c?a:a.filter(function(b){return 0<b.seatsAvailable||b.locked});if("M"+a.map(function(b){return b.URLcode}).join()==app.savedCourseGenerator)return app.courses_generator||new Lazy([]);"A"==app.savedCourseGenerator[0]&&null!=app.course&&(app.courses_generator&&app.courses_generator.get(app.course_list_selection)&&
(c=app.courses_generator.get(app.course_list_selection),a=Array.isArray(c)?c:[]),app.course=a.filter(function(b){return null!==app.course&&b.home==app.courses[app.course].home})[0].index,document.getElementById("selectBox").value=app.course.toString());app.savedCourseGenerator="M"+a.map(function(b){return b.URLcode}).join();app.courses_generator=new Lazy(a);return app.courses_generator}if("A"+app.removeDuplicatesBy(function(b){return b.home},a).map(function(b){return b.home.URLcode}).filter(function(b){return b}).join()+
(app.closed?"C":"")==app.savedCourseGenerator)return app.courses_generator||new Lazy([]);"M"==app.savedCourseGenerator[0]&&app.course&&(app.course=app.courses[app.course].home.index,document.getElementById("selectBox").value=app.course.toString());app.course_list_selection=0;c=document.getElementById("Range");c.max=0;c.value=0;app.courses_generator=(new Lazy(app.cartesianProduct(app.removeDuplicatesBy(function(b){return b.home},a).reduce(function(b,d){d.home.alts.forEach(function(e){var g=e.filter(function(k){return k.locked});
g.length?e=g:a.forEach(function(k){e.includes(k)&&(e=e.filter(function(n){return n!=k}),e.unshift(k))});b.push(app.closed?e:e.filter(function(k){return 0<k.seatsAvailable||k.locked}))});return b},[])))).filter(app.schedCompat);app.savedCourseGenerator="A"+app.removeDuplicatesBy(function(b){return b.home},a).map(function(b){return b.home.URLcode}).filter(function(b){return b}).join()+(app.closed?"C":"");return app.courses_generator};
app.removeDuplicatesBy=function(a,c){var b=new Set;return c.filter(function(d){d=a(d);var e=!b.has(d);e&&b.add(d);return e})};
app.cartesianProduct=function $jscomp$generator$function(a){var b,d,e;return $jscomp.generator.createGenerator($jscomp$generator$function,function(g){switch(g.nextAddress){case 1:if(a.map(function(k){return 0==k.length}).reduce(function(k,n){return k||n},!1))return g.return();if(!(1>=a.length)){g.jumpTo(2);break}b=0;case 3:if(!(b<a[0].length)){g.jumpTo(5);break}return g.yield([a[0][b]],4);case 4:++b;g.jumpTo(3);break;case 5:return g.return();case 2:d=Array(a.length).fill(0,0,a.length);case 7:for(b=
0;b<d.length-1;++b)d[b]>a[b].length-1&&(d[b]=0,d[b+1]++);if(d[d.length-1]>a[a.length-1].length-1)return g.return();e=Array(a.length-1);for(b=0;b<a.length;++b)e[b]=a[b][d[b]];return g.yield(e,9);case 9:d[0]++,g.jumpTo(7)}})};app.schedCompat=function(a){if(1==a.length)return!0;for(var c=[a[0]],b=1;b<a.length;){for(var d=0;d<c.length;++d)if(!app.courseCompat(c[d],a[b]))return!1;c.push(a[b++])}return!0};
app.courseCompat=function(a,c){return a.meetings.reduce(function(b,d){return b&&c.meetings.reduce(function(e,g){return e&&app.meetingCompat(d,g)},!0)},!0)};app.meetingCompat=function(a,c){return"monday tuesday wednesday thursday friday saturday sunday".split(" ").reduce(function(b,d){return b||a[d]&&c[d]},!1)?!(a.beginTime>=c.beginTime&&a.beginTime<c.endTime||a.endTime>c.beginTime&&a.endTime<=c.endTime||c.endTime>a.beginTime&&c.endTime<=a.endTime||c.endTime>a.beginTime&&c.endTime<=a.endTime):!0};window.onload=function(){void 0==window.localStorage.lastSaved&&(window.localStorage.lastSaved="");void 0==window.localStorage.schedules&&(window.localStorage.schedules="{}");void 0==window.localStorage.darkMode&&(window.localStorage.darkMode="false");void 0==window.localStorage.darkMode&&(window.localStorage.darkMode="false");var a=document.getElementById("styleSlider");a.checked="true"==window.localStorage.darkMode;change_style(a);app.mode=document.getElementById("Manual").checked?"Manual":"Automatic";
app.closed=!!app.getHash().split("&")[1];document.getElementById("closedCheck").checked=app.closed;app_config.CORStest?(new Searcher("test")).start(function(d){d?(document.getElementById("loading").style.display="none",document.getElementById("main").style.display=""):(document.getElementById("loading").style.display="none",document.getElementById("cors").style.display="")}):(document.getElementById("loading").style.display="none",document.getElementById("main").style.display="");(new Searcher("terms")).start(function(d){app.terms=
app_config.PROCESSgetTerms(d);d=(app.getHash().split("=")[1]||"").split("&")[0].length?app.terms.map(function(e){return e.URLcode}).indexOf(app.getHash().split("=")[0].substr(1)):-1;(app.getHash().split("=")[1]||"").split("&")[0].length&&-1<d?(app.term=app.terms[d].URLcode,app.updateTerms(),app.changedTerm("first")):(app.term=app.terms[0].URLcode,app.updateTerms(),app.changedTerm(!1));document.getElementById("termSelect").value=app.term;app.updateSaved()});var c=document.getElementById("nextButton"),
b={waiter:null,advanceNextButton:function(d){app.genNext(c);b.waiter=setTimeout(b.advanceNextButton,1)},pressingDown:function(d){app.genNext(c);b.waiter=setTimeout(b.advanceNextButton,750)},notPressingDown:function(d){clearTimeout(b.waiter);b.waiter=null}};c.addEventListener("mousedown",b.pressingDown,!1);c.addEventListener("mouseup",b.notPressingDown,!1);c.addEventListener("mouseleave",b.notPressingDown,!1);c.addEventListener("touchstart",b.pressingDown,!1);c.addEventListener("touchend",b.notPressingDown,
!1)};
